#!/bin/sh

bspc rule -a Arandr state=floating
bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule  -a code-oss desktop='^2' follow=on
bspc rule  -a Geany desktop='^2' follow=on
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a -stable desktop='^6' follow=on
#bspc rule -a -snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
bspc rule -a Thunar desktop='^6' follow=on
bspc rule -a discord desktop='^9' follow=on
bspc rule -a Spotify desktop='^10' follow=on
bspc rule -a nuclear desktop='^10' follow=on 
#Spotify fix  --move desktop 10
sleep 1
wmctrl -r Spotify -t 10
exit
##External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window