#!/bin/sh
#          
#              _          _  _   ___  
#  __   _____ (_) ___ ___| || | / _ \ 
#  \ \ / / _ \| |/ __/ _ \ || || (_) |
#   \ V / (_) | | (_|  __/__   _\__, |
#    \_/ \___/|_|\___\___|  |_|   /_/ 
                                   






#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#1e1f29"
bspc config active_border_color		" #9C9C9C"
bspc config focused_border_color	"#8e24aa"
bspc config presel_feedback_color	" #ff79c6"
#bspc config urgbspc rule -a Arandr state=floating 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
bspc monitor DP-1   -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9 10

#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating
bspc rule -a Tilix state=floating
bspc rule -a google-chrome-stable state=floating
bspc rule -a termite state=floating
bspc rule -a caprine state=floating
bspc rule -a Yad state=floating
bspc rule -a Yad-calenda state=floating
bspc rule -a yad state=floating
bspc rule -a yad-calenda state=floating
bspc rule -a Stremio state=floating
bspc rule -a stremio state=floating



bspc rule -a Arandr state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

#open applications on specific workspaces
bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Brave-browser desktop='^1' follow=on
#bspc rule -a caprine desktop='^1'  follow=on
bspc rule -a Firefox desktop='^1'  follow=on
bspc rule  -a code-oss desktop='^2' follow=on
bspc rule  -a Geany desktop='^2' follow=on
bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a -stable desktop='^6' follow=on
#bspc rule -a -snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
bspc rule -a Thunar desktop='^6' follow=on
bspc rule -a discord desktop='^9' follow=on
bspc rule -a Spotify desktop='^10' follow=on
#bspc rule -a nuclear desktop='^10' follow=on 
bspc rule -a stremio desktop='^10' follow=on 
bspc rule -a Stremio desktop='^10' follow=on 


#Spotify fix  --move desktop 10
sleep 1
wmctrl -r Spotify -t 10
exit

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
